version: 1.0.{build}
image: Visual Studio 2019
build_script:
  - ps: >-
      git submodule update --init --recursive
      
      Invoke-WebRequest -uri 'https://www.libsdl.org/release/SDL2-2.0.12.zip' -OutFile 'SDL2.zip'
      
      Expand-Archive -Path 'SDL2.zip' -DestinationPath '.' -Force
      
      ren SDL2-2.0.12 SDL2

      mkdir CSMoE-Full\csmoe
      mkdir CSMoE-Full\cstrike
      mkdir CSMoE-Full\valve
      
      nuget restore msvc/csmoe.sln

      cp -r msvc\packages\ANGLE.WindowsStore.2.1.13\bin\UAP\ARM msvc\packages\ANGLE.WindowsStore.Servo.2.1.20\bin\UAP\
      ren msvc\packages\ANGLE.WindowsStore.Servo.2.1.20\bin\UAP\x86 Win32
      
      (Get-Content SDL2\VisualC-WinRT\UWP_VS2015\SDL-UWP.vcxproj) | %{$_ -replace "<PlatformToolset>v140</PlatformToolset>", "<PlatformToolset>v142</PlatformToolset>"} | %{$_ -replace "<WindowsTargetPlatformVersion>10.0.10240.0</WindowsTargetPlatformVersion>", "<WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>"} | Set-Content SDL2\VisualC-WinRT\UWP_VS2015\SDL-UWP.vcxproj
      
      & msbuild "C:\projects\csmoe\msvc\csmoe.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:AppxBundle=false